### ISSUE TITLE
Feature Request: Create API Key to file

### ISSUE THREAD

**Issue by danetuso** [nathan-fiscaletti/synful#155]
I'd like to be able to be able to do:
`./synful -ck AUTH_HANDLE 'test@test.com' 10 0 -out path/to/.AUTH_HANDLE_PRIVATE_API_KEY.txt`
In other words I need a way to automatically grab the key generated from running the -ck command without having to parse the stdout.

**Comment by nathan-fiscaletti** [comment]
You can use the following command to do this:

```
echo `./synful -o 0 -ck AUTH_HANDLE test@test.com 10 0` > path/to/AUTH_HANDLE_PRIVATE_API_KEY.txt
```

See [the -output (-o) command in Other Commands](https://github.com/nathan-fiscaletti/synful/wiki/CLI-Usage-Run-Through#other-commands)

> Note: The -output command *must* be used before the -ck command in order for it to work properly.
